# Generated by Django 5.2.1 on 2025-09-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0002_order_orderitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
